<?php
declare(strict_types=1);

namespace Panth\AdvancedSEO\Setup\Patch\Data;

use Magento\Framework\Setup\ModuleDataSetupInterface;
use Magento\Framework\Setup\Patch\DataPatchInterface;
use Magento\Store\Model\StoreManagerInterface;

/**
 * Registers the url_rewrite row mapping the public path /llms-full.txt
 * to the internal seo/llms/full frontend controller.
 *
 * Split from InstallSeoUrlRewrites so existing installs (which already ran
 * that patch) still register this additional endpoint.
 */
class InstallLlmsFullUrlRewrite implements DataPatchInterface
{
    private const REQUEST_PATH = 'llms-full.txt';
    private const TARGET_PATH  = 'seo/llms/full';

    public function __construct(
        private readonly ModuleDataSetupInterface $moduleDataSetup,
        private readonly StoreManagerInterface $storeManager
    ) {
    }

    public static function getDependencies(): array
    {
        return [InstallSeoUrlRewrites::class];
    }

    public function getAliases(): array
    {
        return [];
    }

    public function apply(): self
    {
        $this->moduleDataSetup->startSetup();

        $connection = $this->moduleDataSetup->getConnection();
        $table = $this->moduleDataSetup->getTable('url_rewrite');

        foreach ($this->storeManager->getStores(true) as $store) {
            $storeId = (int) $store->getId();
            $exists = (int) $connection->fetchOne(
                $connection->select()
                    ->from($table, ['url_rewrite_id'])
                    ->where('request_path = ?', self::REQUEST_PATH)
                    ->where('store_id = ?', $storeId)
                    ->where('entity_type = ?', 'custom')
                    ->limit(1)
            );
            if ($exists > 0) {
                continue;
            }
            try {
                $connection->insert($table, [
                    'entity_type'      => 'custom',
                    'entity_id'        => 0,
                    'request_path'     => self::REQUEST_PATH,
                    'target_path'      => self::TARGET_PATH,
                    'redirect_type'    => 0,
                    'store_id'         => $storeId,
                    'description'      => 'Panth_AdvancedSEO llms-full.txt endpoint',
                    'is_autogenerated' => 0,
                    'metadata'         => null,
                ]);
            } catch (\Throwable) {
                // Ignore duplicates / race conditions.
            }
        }

        $this->moduleDataSetup->endSetup();

        return $this;
    }
}
