<?php
declare(strict_types=1);

namespace Panth\AdvancedSEO\Setup\Patch\Data;

use Magento\Framework\Setup\ModuleDataSetupInterface;
use Magento\Framework\Setup\Patch\DataPatchInterface;
use Magento\Store\Model\StoreManagerInterface;

/**
 * Registers url_rewrite rows mapping the public paths /robots.txt, /llms.txt,
 * /llms-full.txt and /panth-sitemap.xml to the internal Panth_AdvancedSEO
 * frontend controllers so they can be served without a custom router.
 *
 * Uses raw url_rewrite inserts (rather than UrlRewrite Service) to keep the
 * patch dependency-free and store-scoped.
 */
class InstallSeoUrlRewrites implements DataPatchInterface
{
    /**
     * @var array<string,string> request_path => target_path
     */
    private const REWRITES = [
        'robots.txt'         => 'seo/robots/index',
        'llms.txt'           => 'seo/llms/index',
        'llms-full.txt'      => 'seo/llms/full',
        'panth-sitemap.xml'  => 'seo/sitemap/index',
    ];

    public function __construct(
        private readonly ModuleDataSetupInterface $moduleDataSetup,
        private readonly StoreManagerInterface $storeManager
    ) {
    }

    public static function getDependencies(): array
    {
        return [];
    }

    public function getAliases(): array
    {
        return [];
    }

    public function apply(): self
    {
        $this->moduleDataSetup->startSetup();

        $connection = $this->moduleDataSetup->getConnection();
        $table = $this->moduleDataSetup->getTable('url_rewrite');

        foreach ($this->storeManager->getStores(true) as $store) {
            $storeId = (int) $store->getId();
            foreach (self::REWRITES as $request => $target) {
                $exists = (int) $connection->fetchOne(
                    $connection->select()
                        ->from($table, ['url_rewrite_id'])
                        ->where('request_path = ?', $request)
                        ->where('store_id = ?', $storeId)
                        ->where('entity_type = ?', 'custom')
                        ->limit(1)
                );
                if ($exists > 0) {
                    continue;
                }
                try {
                    $connection->insert($table, [
                        'entity_type'     => 'custom',
                        'entity_id'       => 0,
                        'request_path'    => $request,
                        'target_path'     => $target,
                        'redirect_type'   => 0,
                        'store_id'        => $storeId,
                        'description'    => 'Panth_AdvancedSEO SEO endpoint',
                        'is_autogenerated' => 0,
                        'metadata'       => null,
                    ]);
                } catch (\Throwable) {
                    // Ignore duplicates/race conditions.
                }
            }
        }

        $this->moduleDataSetup->endSetup();

        return $this;
    }
}
